### ISSUE TITLE
Nothing blink with ComponentWillMount is deprecated warning

### ISSUE THREAD

**Issue by to175** [BricePissard/react-native-blink-view#1]
Hello, I cannot use blinking text, help me please :)

In my code I have added : **import BlinkView from 'react-native-blink-view';**

One of the error is : **ComponentWillMount is deprecated**... and nothing is blinking... I also sais I need to updates a lot of components but I have the last version of react native...

What is the problem please ?

**Comment by AfanasievN** [comment]
Share your code :)
