### ISSUE TITLE
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by mitchobrian** [BricePissard/react-native-blink-view#4]
With the last update of react we need to add the **useNativeDriver** Option...

**Comment by mitchobrian** [comment]
Or should we set it to useNativeDriver: false ?
I tried both, false is working fine...

**Comment by crackedbeefcake** [comment]
+1 please publish a new  version

**Comment by kd-s-t** [comment]
this is happening to me... don't know where to set `useNativeDriver: false`

**Comment by Umer-Hassan** [comment]
@ollolollollooloo just go to "node_modules/react-native-blink-view/BlinkView.js".. check the screenshot.
![Capture](https://user-images.githubusercontent.com/68000747/124577512-c3ec3600-de66-11eb-9bf2-79fc97d1e071.PNG)

**Comment by BricePissard** [comment]
Sorry for the delay, I've pushed the correction, you should have to simply update the lib.
